name: cheffromhell
favicon: null
layout_spectrum: 1
typography_spectrum: 0.09378
title: hot as hell in the kitchen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#ffffff'
    - '#684935'
    - '#fff100'
    - '#00951e'
  brandStrength: 0.3125
  lightness: 0.895443317713216
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
