name: cheffromhell
favicon: null
layout_spectrum: 0.3788
typography_spectrum: 0.19214
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2d02d'
    - '#1588c9'
    - '#668917'
    - '#e6411b'
    - '#563807'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
