name: cheffromhell
favicon: null
layout_spectrum: 0.7735618415754288
typography_spectrum: 0.2542696129530668
title: hot as hell in the kitchen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.17110040574334562
  lightness: 0.895443317713216
  saturation: 0.6814100500196218
  rhythmicContrast: 0.07114845584146678
purpose: []
