name: cheffromhell
favicon: null
layout_spectrum: 0.95062
typography_spectrum: 0.09378
title: hot as hell in the kitchen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#ffffff'
    - '#684935'
    - '#fff100'
    - '#00951e'
  brandStrength: 0.3125
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
