name: cheffromhell
favicon: null
layout_spectrum: 0.92557
typography_spectrum: 0.19214
title: hot as hell in the kitchen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#677c77'
    - '#252e2d'
    - '#96b4b2'
    - '#cffdfd'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
