name: cheffromhell
favicon: null
layout_spectrum: 0.9129
typography_spectrum: 0.19214
title: hot as hell in the kitchen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e7e8'
    - '#171111'
    - '#bbb4b6'
    - '#6e696f'
    - '#f3352f'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
